apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hello
    apps.tanzu.vmware.com/has-tests: true
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: ssh://git@ssh.dev.azure.com/v3/doddatvmware/tap-lab-canary-app/hello
